apiVersion : apps/v1
kind: Deployment
metadata:
  name: photostudio-backend
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: photostudio
    template:
      metadata:
        labels: 
          app: photostudio
      spec:
        containers:
        - name: photostudio
          image: photostudioacr2.azurecr.io/photostudio:1.0
          ports:
          - containerPort: 3000
          imagePullPolicy: Always
      
