apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: photostudio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/prosenjitdevops/PhotoStudioNew.git
    targetRevision: main
    path: helm/photostudio
  destination:
    server: https://kubernetes.default.svc
    namespace: photostudio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
